### ISSUE TITLE
Inference script: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ranjeetds** [icml-2020-nlp/semsim#1]
While inferencing the model getting this above error at ```data_name_or_path='cnn_dm-bin'``` 

I have not tuned ```BART``` model. I downloaded semsim pretrained model and trying to use it for inference on test data set.

**Comment by icml-2020-nlp** [comment]
Hi, 
Thank you for your interests on our work. 
You need to generated `cnn_dm-bin` by following [2) BPE preprocess and 3) Binarize dataset](https://github.com/icml-2020-nlp/semsim#2-bpe-preprocess) just as when you finetune the model.
Sorry for the confusion and I will update the README
Thanks!

**Comment by ranjeetds** [comment]
Thank you very much for the prompt response. Will follow the steps you have mentioned.

**Comment by ranjeetds** [comment]
@icml-2020-nlp could you please mention that step 2) BPE preprocess commands are bash commands so that they needs to be run through terminal itself (Even though it is apperent it creates confusion at first)

**Comment by icml-2020-nlp** [comment]
@ranjeetds Thank you!

**Comment by ranjeetds** [comment]
@icml-2020-nlp not able to find ```fairseq-preprocess``` for running step 3 to binarize data

**Comment by icml-2020-nlp** [comment]
Hi @ranjeetds ,
Have you installed `fairseq == 0.8.0` ?
```bash
pip install fairseq == 0.8.0
```

**Comment by ranjeetds** [comment]
@icml-2020-nlp no.

**Comment by icml-2020-nlp** [comment]
@ranjeetds 
As we mentioned in [here](https://github.com/icml-2020-nlp/semsim#for-fine-tuning-and-inferencing-), you need to install 
```
fairseq == 0.8.0
``` 
AND 
```
cd fairseq-semsim
pip install --editable .
```
Would you please proceed with the pre-processing steps after you install `fairseq == 0.8.0` and let us know the results?

I am checking the code once again and also thinking of making some `requirement.txt`....
Thanks for letting us know!

**Comment by icml-2020-nlp** [comment]
Fyi you need `python3-dev` to install fairseq
```bash
sudo apt-get install python3-dev
```

**Comment by ranjeetds** [comment]
Hi @icml-2020-nlp, Thank you very much for your valuable response. Got everything working fine. Thank you very much.
